### ISSUE TITLE
Does ddnsadmin handle MX record preference?

### ISSUE THREAD

**Issue by edgreenberg** [fln/ddnsadmin#1]
Near as I can tell, there is no provision to add MX records with preference.  Am I missing something?

**Comment by fln** [comment]
Ddnsadmin allows setting MX records preference. The "Data" field should have the "preference hostanme" format for MX records.

Examples:
- 10 mx1.example.net.
- 20 mx2.example.net.

This tools supports all DNS record types that are supported by PHP http://pear.php.net/package/Net_DNS2 library. I have tested adding MX records with preference via this tool.

**Comment by edgreenberg** [comment]
Thank you. I see how it works now.

On February 22, 2016 2:12:40 PM EST, fln notifications@github.com wrote:

> Ddnsadmin allows setting MX records preference. The "Data" field should
> have the "preference hostanme" format for MX records.
> 
> Examples:
> - 10 mx1.example.net.
> - 20 mx2.example.net.
> 
> This tools supports all DNS record types that are supported by PHP
> http://pear.php.net/package/Net_DNS2 library. I have tested adding MX
> records with preference via this tool.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fln/ddnsadmin/issues/1#issuecomment-187325317

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
